### ISSUE TITLE
MQTT topic prefix isn't always SMART/HILD

### ISSUE THREAD

**Issue by Adoruta** [scooter1556/glow-mqtt#1]
Octopus Energy provide the Glowstick however the topic prefix is SMART/OCT/ instead of SMART/HILD/ . Could this be supported? Maybe instead of specifying just the Device ID, the full topic is requested, in case there are other energy customers using this product?

**Comment by Adoruta** [comment]
As a workaround, I used a bit of Node-RED to copy the contents of the payload from SMART/OCT/xxx to SMART/HILD/xxx and then the existing package works as expected.

**Comment by srware** [comment]
@Adoruta I didn't realise Octopus Energy also offer such a product. Happy to add support for this. I will add a 'glow_provider' parameter which will allow overriding this part of the topic.

Thanks
