### ISSUE TITLE
Requirement for protection from 0 readings

### ISSUE THREAD

**Issue by Twincarb** [scooter1556/glow-mqtt#3]
With my Gas supply I am seeing the reading dip to `0` at 00:00 and 03:00 each day the next reading is the correct one, it would be very useful for readings which are `state_class: total_increasing` to have a catch to prevent them from providing a erroneous reading. The only time this would happen is if the meter itself is replaced.
This appears to have been noticed on the ndfred page https://gist.github.com/ndfred/5bb51b567f8cfaf2bb06da6393169321?permalink_comment_id=4126127#gistcomment-4126127

**Comment by scooter1556** [comment]
I can put in a check to make sure readings are greater than 0 before publishing. I'll take a look :)

**Comment by scooter1556** [comment]
@Twincarb ,

Can you please test latest code in 'main' branch to see if this fixes the issue for you?

**Comment by Twincarb** [comment]
I can, although I am not certain on the best way to locally edit. I am able to ssh into my hassio instance and then navigate into your docker instance. Can I just edit the glow2mqtt.py and save it (I am happy with using VI for editing)? would the addon need restarting?

**Comment by scooter1556** [comment]
I wouldn't really recommend messing with your Hass instance. Let me push an addon update and hope for the best :)

**Comment by Twincarb** [comment]
Not a problem, I can test both the gas and electric on update and the code is simple enough

**Comment by Twincarb** [comment]
On the latest version now, so far both gas and electric is coming in as expected. Will check again in the morning to check the 0 values are ignored. Many thanks @scooter1556

**Comment by Twincarb** [comment]
All good from my point of view, the 0 readings are no longer being saved and putting out all my figures :) many thanks @scooter1556
